services:
  ddnss:
    image: ddnss:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ddnss
    ports:
      - 5533:5533
    volumes:
      - ./data:/ddnss/data
    environment:
      - CLOUDFLARE_API_TOKEN = 123456

      # - AUTH_ENABLE = False
      # - AUTH_USERNAME = admin
      # - AUTH_PASSWORD = 123456

      # - TZ=Asia/Shanghai
    restart: always
