#SQLALCHEMY_DATABASE_URI: sqlite:///app.db
SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:123456@localhost:3306/ddns
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_ECHO: True

AUTH:
  key: a2a520cf51a34a628fc857a6d859e812
  email: xxx@qq.com
  zone:
    id: fc857a4a6282ca3a520f51a6d859e812
    name: example.com